//! Action execution port used by transport adapters.

use async_trait::async_trait;
use orbitrelay_protocol::{Action, Event};

use crate::TransportExecutionError;

/// Executes protocol actions without exposing a concrete runtime to transport.
#[async_trait]
pub trait ActionExecutor: Send + Sync {
    /// Executes one action and returns all events generated by that execution.
    async fn execute(&self, action: Action) -> Result<Vec<Event>, TransportExecutionError>;
}
